In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv("/content/sample_data/iris.csv")

In [31]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [32]:
df.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [33]:
x = df.drop('variety',axis=1)
y = df.variety

In [34]:
x.head()

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [35]:
y.head()

0    Setosa
1    Setosa
2    Setosa
3    Setosa
4    Setosa
Name: variety, dtype: object

In [36]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y = lb.fit_transform(df.variety)

In [37]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [38]:
df["species"] = y

In [39]:
df.head(10)

sepal.length  sepal.width  petal.length  petal.width variety  species
0           5.1          3.5           1.4          0.2  Setosa        0
1           4.9          3.0           1.4          0.2  Setosa        0
2           4.7          3.2           1.3          0.2  Setosa        0
3           4.6          3.1           1.5          0.2  Setosa        0
4           5.0          3.6           1.4          0.2  Setosa        0
5           5.4          3.9           1.7          0.4  Setosa        0
6           4.6          3.4           1.4          0.3  Setosa        0
7           5.0          3.4           1.5          0.2  Setosa        0
8           4.4          2.9           1.4          0.2  Setosa        0
9           4.9          3.1           1.5          0.1  Setosa        0

In [40]:
df.species.value_counts()

0    50
1    50
2    50
Name: species, dtype: int64

In [41]:
df.variety.value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [44]:
print(x_train.shape)
print(x_test.shape)

(105, 4)
(45, 4)


In [45]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [46]:
model = Sequential()
model.add(Dense(10,input_shape=(4,),activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [47]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 10)                50        
                                                                 
 dense_4 (Dense)             (None, 8)                 88        
                                                                 
 dense_5 (Dense)             (None, 3)                 27        
                                                                 
Total params: 165
Trainable params: 165
Non-trainable params: 0
_________________________________________________________________


In [48]:
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy", metrics=['accuracy'])

In [49]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 3ms/step - loss: 1.9544 - accuracy: 0.3429
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.8909 - accuracy: 0.3429
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.8290 - accuracy: 0.3429
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 1.7677 - accuracy: 0.3429
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 1.7150 - accuracy: 0.3429
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 1.6648 - accuracy: 0.3429
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 1.6140 - accuracy: 0.3429
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 1.5723 - accuracy: 0.3429
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 1.5304 - accuracy: 0.3429
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 1.4930 - accuracy: 0.3429
Epoch 11/100
4/4 [===========

In [50]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 6ms/step - loss: 0.5431 - accuracy: 0.9778


[0.543067991733551, 0.9777777791023254]

In [51]:
y_pred = model.predict(x_test)

2/2 [==============================] - 0s 4ms/step


In [52]:
y_pred[:10]

array([[0.92664534, 0.05310554, 0.02024905],
       [0.2743051 , 0.46080777, 0.26488703],
       [0.96312076, 0.02754389, 0.00933543],
       [0.27054775, 0.33236825, 0.397084  ],
       [0.26350567, 0.19670701, 0.5397873 ],
       [0.26222226, 0.17821696, 0.5595608 ],
       [0.9299572 , 0.04988358, 0.02015913],
       [0.27345952, 0.2517055 , 0.474835  ],
       [0.25777996, 0.43142834, 0.31079164],
       [0.27390245, 0.2595634 , 0.4665341 ]], dtype=float32)

In [53]:
y_pred=np.argmax(y_pred,axis=1)
print(y_pred)

[0 1 0 2 2 2 0 2 1 2 0 1 2 2 0 2 2 2 1 1 2 1 1 2 1 2 2 0 1 0 0 2 1 0 0 0 0
 2 2 2 2 1 0 1 0]


In [54]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test,y_pred)
score = accuracy_score(y_test,y_pred)
print(cm)
print("score is : ",score)

[[14  0  0]
 [ 0 12  1]
 [ 0  0 18]]
score is :  0.9777777777777777


In [55]:
len(y_test)

45

In [56]:
len(y_pred)

45